import httpService from './http-service'

export async function findTopAlbums(limit = 10): Promise<TopAlbumsResponse> {
  const response = await httpService.get<TopAlbumsResponse>(
    `https://itunes.apple.com/us/rss/topalbums/limit=${limit}/json`
  )
  return response.data
}

// Generated by https://transform.tools/json-to-typescript
export type TopAlbumsResponse = {
  feed: Feed
}

type Feed = {
  author: Author
  entry: Entry[]
  updated: Updated
  rights: Rights2
  title: Title2
  icon: Icon
  link: Link2[]
  id: Id2
}

type Author = {
  name: Name
  uri: Uri
}

type Name = {
  label: string
}

type Uri = {
  label: string
}

type Entry = {
  'im:name': ImName
  'im:image': ImImage[]
  'im:itemCount': ImItemCount
  'im:price': ImPrice
  'im:contentType': ImContentType
  rights: Rights
  title: Title
  link: Link
  id: Id
  'im:artist': ImArtist
  category: Category
  'im:releaseDate': ImReleaseDate
}

type ImName = {
  label: string
}

type ImImage = {
  label: string
  attributes: Attributes
}

type Attributes = {
  height: string
}

type ImItemCount = {
  label: string
}

type ImPrice = {
  label: string
  attributes: Attributes2
}

type Attributes2 = {
  amount: string
  currency: string
}

type ImContentType = {
  'im:contentType': ImContentType2
  attributes: Attributes4
}

type ImContentType2 = {
  attributes: Attributes3
}

type Attributes3 = {
  term: string
  label: string
}

type Attributes4 = {
  term: string
  label: string
}

type Rights = {
  label: string
}

type Title = {
  label: string
}

type Link = {
  attributes: Attributes5
}

type Attributes5 = {
  rel: string
  type: string
  href: string
}

type Id = {
  label: string
  attributes: Attributes6
}

type Attributes6 = {
  'im:id': string
}

type ImArtist = {
  label: string
  attributes?: Attributes7
}

type Attributes7 = {
  href: string
}

type Category = {
  attributes: Attributes8
}

type Attributes8 = {
  'im:id': string
  term: string
  scheme: string
  label: string
}

type ImReleaseDate = {
  label: string
  attributes: Attributes9
}

type Attributes9 = {
  label: string
}

type Updated = {
  label: string
}

type Rights2 = {
  label: string
}

type Title2 = {
  label: string
}

type Icon = {
  label: string
}

type Link2 = {
  attributes: Attributes10
}

type Attributes10 = {
  rel: string
  type?: string
  href: string
}

type Id2 = {
  label: string
}
